USE DomSun
DECLARE @_T table(R_ID INT IDENTITY(0,1), NAME VARCHAR(512),P VARCHAR(35), S VARCHAR(75))
DECLARE @_T2 table(R_ID INT IDENTITY(0,1), MEM_ID VARCHAR(20), NAME VARCHAR(512), STATE VARCHAR(3), NUM_RCRDS_RTND INT)
DECLARE @_T4 table(R_ID INT IDENTITY(0,1), MEM_ID VARCHAR(20), NAME VARCHAR(512), STATE VARCHAR(75), NUM_RCRDS_RTND INT)
DECLARE @_T3 table(MEM_ID VARCHAR(20), NAME VARCHAR(512), STATE VARCHAR(3))
declare @_MEM_NAME VARCHAR(75), @_R_ID INT, @_C INT = 0, @_P VARCHAR(35), @_S VARCHAR(75), 

@_DATE_BILL_VOTED_ON VARCHAR(20)='FEB 03, 1994', @_CONG_NUM INT = 103
INSERT INTO @_T
VALUES('Abercrombie','Democratic','Hawaii'),
('Ackerman','Democratic','New York'),
('Allard','Republican','Colorado'),
('Andrews (ME)','Democratic','Maine'),
('Andrews','Democratic','New Jersey'),
('Andrews (TX)','Democratic','Texas'),
('Applegate','Democratic','Ohio'),
('Archer','Republican','Texas'),
('Armey','Republican','Texas'),
('Bacchus (FL)','Democratic','Florida'),
('Bachus','Republican','Alabama'),
('Baesler','Democratic','Kentucky'),
('Baker (CA)','Republican','California'),
('Baker (LA)','Republican','Louisiana'),
('Ballenger','Republican','North Carolina'),
('Barca','Democratic','Wisconsin'),
('Barcia','Democratic','Michigan'),
('Barlow','Democratic','Kentucky'),
('Barrett (NE)','Republican','Nebraska'),
('Barrett (WI)','Democratic','Wisconsin'),
('Bartlett','Republican','Maryland'),
('Barton','Republican','Texas'),
('Bateman','Republican','Virginia'),
('Becerra','Democratic','California'),
('Beilenson','Democratic','California'),
('Bentley','Republican','Maryland'),
('Bereuter','Republican','Nebraska'),
('Berman','Democratic','California'),
('Bevill','Democratic','Alabama'),
('Bilbray','Democratic','Nevada'),
('Bilirakis','Republican','Florida'),
('Bishop','Democratic','Georgia'),
('Blackwell','Democratic','Pennsylvania'),
('Bliley','Republican','Virginia'),
('Blute','Republican','Massachusetts'),
('Boehlert','Republican','New York'),
('Boehner','Republican','Ohio'),
('Bonilla','Republican','Texas'),
('Bonior','Democratic','Michigan'),
('Borski','Democratic','Pennsylvania'),
('Boucher','Democratic','Virginia'),
('Brewster','Democratic','Oklahoma'),
('Brooks','Democratic','Texas'),
('Browder','Democratic','Alabama'),
('Brown (CA)','Democratic','California'),
('Brown (FL)','Democratic','Florida'),
('Brown (OH)','Democratic','Ohio'),
('Bryant (TX)','Democratic','Texas'),
('Bunning','Republican','Kentucky'),
('Burton','Republican','Indiana'),
('Buyer','Republican','Indiana'),
('Byrne','Democratic','Virginia'),
('Callahan','Republican','Alabama'),
('Calvert','Republican','California'),
('Camp','Republican','Michigan'),
('Canady','Republican','Florida'),
('Cantwell','Democratic','Washington'),
('Cardin','Democratic','Maryland'),
('Carr','Democratic','Michigan'),
('Castle','Republican','Delaware'),
('Chapman','Democratic','Texas'),
('Clay','Democratic','Missouri'),
('Clayton','Democratic','North Carolina'),
('Clement','Democratic','Tennessee'),
('Clinger','Republican','Pennsylvania'),
('Clyburn','Democratic','South Carolina'),
('Coble','Republican','North Carolina'),
('Coleman','Democratic','Texas'),
('Collins (GA)','Republican','Georgia'),
('Collins (IL)','Democratic','Illinois'),
('Collins (MI)','Democratic','Michigan'),
('Combest','Republican','Texas'),
('Condit','Democratic','California'),
('Conyers','Democratic','Michigan'),
('Cooper','Democratic','Tennessee'),
('Coppersmith','Democratic','Arizona'),
('Costello','Democratic','Illinois'),
('Cox','Republican','California'),
('Coyne','Democratic','Pennsylvania'),
('Cramer','Democratic','Alabama'),
('Crane','Republican','Illinois'),
('Crapo','Republican','Idaho'),
('Cunningham','Republican','California'),
('Danner','Democratic','Missouri'),
('Darden','Democratic','Georgia'),
('de la Garza','Democratic','Texas'),
('de Lugo (VI)','Democratic','(Unknown)'),
('Deal','Democratic','Georgia'),
('DeFazio','Democratic','Oregon'),
('DeLauro','Democratic','Connecticut'),
('DeLay','Republican','Texas'),
('Dellums','Democratic','California'),
('Derrick','Democratic','South Carolina'),
('Deutsch','Democratic','Florida'),
('Diaz-Balart','Republican','Florida'),
('Dickey','Republican','Arkansas'),
('Dicks','Democratic','Washington'),
('Dingell','Democratic','Michigan'),
('Dixon','Democratic','California'),
('Dooley','Democratic','California'),
('Doolittle','Republican','California'),
('Dornan','Republican','California'),
('Dreier','Republican','California'),
('Duncan','Republican','Tennessee'),
('Dunn','Republican','Washington'),
('Durbin','Democratic','Illinois'),
('Edwards (CA)','Democratic','California'),
('Edwards','Democratic','Texas'),
('Ehlers','Republican','Michigan'),
('Emerson','Republican','Missouri'),
('Engel','Democratic','New York'),
('English (AZ)','Democratic','Arizona'),
('Eshoo','Democratic','California'),
('Evans','Democratic','Illinois'),
('Everett','Republican','Alabama'),
('Ewing','Republican','Illinois'),
('Faleomavaega (AS)','Democratic','(Unknown)'),
('Farr','Democratic','California'),
('Fawell','Republican','Illinois'),
('Fazio','Democratic','California'),
('Fields (LA)','Democratic','Louisiana'),
('Fields (TX)','Republican','Texas'),
('Filner','Democratic','California'),
('Fingerhut','Democratic','Ohio'),
('Fish','Republican','New York'),
('Flake','Democratic','New York'),
('Foglietta','Democratic','Pennsylvania'),
('Foley','Democratic','Washington'),
('Ford (MI)','Democratic','Michigan'),
('Ford','Democratic','Tennessee'),
('Fowler','Republican','Florida'),
('Frank (MA)','Democratic','Massachusetts'),
('Franks (CT)','Republican','Connecticut'),
('Franks (NJ)','Republican','New Jersey'),
('Frost','Democratic','Texas'),
('Furse','Democratic','Oregon'),
('Gallegly','Republican','California'),
('Gallo','Republican','New Jersey'),
('Gejdenson','Democratic','Connecticut'),
('Gekas','Republican','Pennsylvania'),
('Gephardt','Democratic','Missouri'),
('Geren','Democratic','Texas'),
('Gibbons','Democratic','Florida'),
('Gilchrest','Republican','Maryland'),
('Gillmor','Republican','Ohio'),
('Gilman','Republican','New York'),
('Gingrich','Republican','Georgia'),
('Glickman','Democratic','Kansas'),
('Gonzalez','Democratic','Texas'),
('Goodlatte','Republican','Virginia'),
('Goodling','Republican','Pennsylvania'),
('Gordon','Democratic','Tennessee'),
('Goss','Republican','Florida'),
('Grams','Republican','Minnesota'),
('Grandy','Republican','Iowa'),
('Green','Democratic','Texas'),
('Greenwood','Republican','Pennsylvania'),
('Gunderson','Republican','Wisconsin'),
('Gutierrez','Democratic','Illinois'),
('Hall (OH)','Democratic','Ohio'),
('Hall (TX)','Democratic','Texas'),
('Hamburg','Democratic','California'),
('Hamilton','Democratic','Indiana'),
('Hancock','Republican','Missouri'),
('Hansen','Republican','Utah'),
('Harman','Democratic','California'),
('Hastert','Republican','Illinois'),
('Hastings (FL)','Democratic','Florida'),
('Hayes','Democratic','Louisiana'),
('Hefley','Republican','Colorado'),
('Hefner','Democratic','North Carolina'),
('Herger','Republican','California'),
('Hilliard','Democratic','Alabama'),
('Hinchey','Democratic','New York'),
('Hoagland','Democratic','Nebraska'),
('Hobson','Republican','Ohio'),
('Hochbrueckner','Democratic','New York'),
('Hoekstra','Republican','Michigan'),
('Hoke','Republican','Ohio'),
('Holden','Democratic','Pennsylvania'),
('Horn','Republican','California'),
('Houghton','Republican','New York'),
('Hoyer','Democratic','Maryland'),
('Huffington','Republican','California'),
('Hughes','Democratic','New Jersey'),
('Hunter','Republican','California'),
('Hutchinson','Republican','Arkansas'),
('Hutto','Democratic','Florida'),
('Hyde','Republican','Illinois'),
('Inglis','Republican','South Carolina'),
('Inhofe','Republican','Oklahoma'),
('Inslee','Democratic','Washington'),
('Istook','Republican','Oklahoma'),
('Jacobs','Democratic','Indiana'),
('Jefferson','Democratic','Louisiana'),
('Johnson (CT)','Republican','Connecticut'),
('Johnson (GA)','Democratic','Georgia'),
('Johnson (SD)','Democratic','South Dakota'),
('Johnson, E. B.','Democratic','Texas'),
('Johnson, Sam','Republican','Texas'),
('Johnston','Democratic','Florida'),
('Kanjorski','Democratic','Pennsylvania'),
('Kaptur','Democratic','Ohio'),
('Kasich','Republican','Ohio'),
('Kennedy (MA)','Democratic','Massachusetts'),
('Kennelly','Democratic','Connecticut'),
('Kildee','Democratic','Michigan'),
('Kim','Republican','California'),
('King','Republican','New York'),
('Kingston','Republican','Georgia'),
('Kleczka','Democratic','Wisconsin'),
('Klein','Democratic','New Jersey'),
('Klink','Democratic','Pennsylvania'),
('Klug','Republican','Wisconsin'),
('Knollenberg','Republican','Michigan'),
('Kolbe','Republican','Arizona'),
('Kopetski','Democratic','Oregon'),
('Kreidler','Democratic','Washington'),
('Kyl','Republican','Arizona'),
('LaFalce','Democratic','New York'),
('Lambert','Democratic','Arkansas'),
('Lancaster','Democratic','North Carolina'),
('Lantos','Democratic','California'),
('LaRocco','Democratic','Idaho'),
('Laughlin','Democratic','Texas'),
('Lazio','Republican','New York'),
('Leach','Republican','Iowa'),
('Lehman','Democratic','California'),
('Levin','Democratic','Michigan'),
('Levy','Republican','New York'),
('Lewis (CA)','Republican','California'),
('Lewis (FL)','Republican','Florida'),
('Lewis (GA)','Democratic','Georgia'),
('Lightfoot','Republican','Iowa'),
('Linder','Republican','Georgia'),
('Lipinski','Democratic','Illinois'),
('Livingston','Republican','Louisiana'),
('Lloyd','Democratic','Tennessee'),
('Long','Democratic','Indiana'),
('Lowey','Democratic','New York'),
('Machtley','Republican','Rhode Island'),
('Maloney','Democratic','New York'),
('Mann','Democratic','Ohio'),
('Manton','Democratic','New York'),
('Manzullo','Republican','Illinois'),
('Margolies-Mezvinsky','Democratic','Pennsylvania'),
('Markey','Democratic','Massachusetts'),
('Martinez','Democratic','California'),
('Matsui','Democratic','California'),
('Mazzoli','Democratic','Kentucky'),
('McCandless','Republican','California'),
('McCloskey','Democratic','Indiana'),
('McCollum','Republican','Florida'),
('McCrery','Republican','Louisiana'),
('McCurdy','Democratic','Oklahoma'),
('McDade','Republican','Pennsylvania'),
('McDermott','Democratic','Washington'),
('McHale','Democratic','Pennsylvania'),
('McHugh','Republican','New York'),
('McInnis','Republican','Colorado'),
('McKeon','Republican','California'),
('McKinney','Democratic','Georgia'),
('McMillan','Republican','North Carolina'),
('McNulty','Democratic','New York'),
('Meehan','Democratic','Massachusetts'),
('Meek','Democratic','Florida'),
('Menendez','Democratic','New Jersey'),
('Meyers','Republican','Kansas'),
('Mfume','Democratic','Maryland'),
('Mica','Republican','Florida'),
('Michel','Republican','Illinois'),
('Miller (CA)','Democratic','California'),
('Miller (FL)','Republican','Florida'),
('Mineta','Democratic','California'),
('Minge','Democratic','Minnesota'),
('Mink','Democratic','Hawaii'),
('Moakley','Democratic','Massachusetts'),
('Molinari','Republican','New York'),
('Mollohan','Democratic','West Virginia'),
('Montgomery','Democratic','Mississippi'),
('Moorhead','Republican','California'),
('Moran','Democratic','Virginia'),
('Morella','Republican','Maryland'),
('Murphy','Democratic','Pennsylvania'),
('Murtha','Democratic','Pennsylvania'),
('Myers','Republican','Indiana'),
('Nadler','Democratic','New York'),
('Natcher','Democratic','Kentucky'),
('Neal','Democratic','Massachusetts'),
('Neal (NC)','Democratic','North Carolina'),
('Norton (DC)','Democratic','(Unknown)'),
('Nussle','Republican','Iowa'),
('Oberstar','Democratic','Minnesota'),
('Obey','Democratic','Wisconsin'),
('Olver','Democratic','Massachusetts'),
('Ortiz','Democratic','Texas'),
('Orton','Democratic','Utah'),
('Owens','Democratic','New York'),
('Oxley','Republican','Ohio'),
('Packard','Republican','California'),
('Pallone','Democratic','New Jersey'),
('Parker','Democratic','Mississippi'),
('Pastor','Democratic','Arizona'),
('Paxon','Republican','New York'),
('Payne (NJ)','Democratic','New Jersey'),
('Payne (VA)','Democratic','Virginia'),
('Pelosi','Democratic','California'),
('Penny','Democratic','Minnesota'),
('Peterson (FL)','Democratic','Florida'),
('Peterson (MN)','Democratic','Minnesota'),
('Petri','Republican','Wisconsin'),
('Pickett','Democratic','Virginia'),
('Pickle','Democratic','Texas'),
('Pombo','Republican','California'),
('Pomeroy','Democratic','North Dakota'),
('Porter','Republican','Illinois'),
('Portman','Republican','Ohio'),
('Poshard','Democratic','Illinois'),
('Price (NC)','Democratic','North Carolina'),
('Pryce','Republican','Ohio'),
('Quillen','Republican','Tennessee'),
('Quinn','Republican','New York'),
('Rahall','Democratic','West Virginia'),
('Ramstad','Republican','Minnesota'),
('Rangel','Democratic','New York'),
('Ravenel','Republican','South Carolina'),
('Reed','Democratic','Rhode Island'),
('Regula','Republican','Ohio'),
('Reynolds','Democratic','Illinois'),
('Richardson','Democratic','New Mexico'),
('Ridge','Republican','Pennsylvania'),
('Roberts','Republican','Kansas'),
('Roemer','Democratic','Indiana'),
('Rogers','Republican','Kentucky'),
('Rohrabacher','Republican','California'),
('Romero-Barcelo (PR)','Democratic','(Unknown)'),
('Ros-Lehtinen','Republican','Florida'),
('Rose','Democratic','North Carolina'),
('Rostenkowski','Democratic','Illinois'),
('Roth','Republican','Wisconsin'),
('Roukema','Republican','New Jersey'),
('Rowland','Democratic','Georgia'),
('Roybal-Allard','Democratic','California'),
('Royce','Republican','California'),
('Rush','Democratic','Illinois'),
('Sabo','Democratic','Minnesota'),
('Sanders','Independent','Vermont'),
('Sangmeister','Democratic','Illinois'),
('Santorum','Republican','Pennsylvania'),
('Sarpalius','Democratic','Texas'),
('Sawyer','Democratic','Ohio'),
('Saxton','Republican','New Jersey'),
('Schaefer','Republican','Colorado'),
('Schenk','Democratic','California'),
('Schiff','Republican','New Mexico'),
('Schroeder','Democratic','Colorado'),
('Schumer','Democratic','New York'),
('Scott','Democratic','Virginia'),
('Sensenbrenner','Republican','Wisconsin'),
('Serrano','Democratic','New York'),
('Sharp','Democratic','Indiana'),
('Shaw','Republican','Florida'),
('Shays','Republican','Connecticut'),
('Shepherd','Democratic','Utah'),
('Shuster','Republican','Pennsylvania'),
('Sisisky','Democratic','Virginia'),
('Skaggs','Democratic','Colorado'),
('Skeen','Republican','New Mexico'),
('Skelton','Democratic','Missouri'),
('Slattery','Democratic','Kansas'),
('Slaughter','Democratic','New York'),
('Smith (IA)','Democratic','Iowa'),
('Smith (MI)','Republican','Michigan'),
('Smith (NJ)','Republican','New Jersey'),
('Smith (OR)','Republican','Oregon'),
('Smith (TX)','Republican','Texas'),
('Snowe','Republican','Maine'),
('Solomon','Republican','New York'),
('Spence','Republican','South Carolina'),
('Spratt','Democratic','South Carolina'),
('Stark','Democratic','California'),
('Stearns','Republican','Florida'),
('Stenholm','Democratic','Texas'),
('Stokes','Democratic','Ohio'),
('Strickland','Democratic','Ohio'),
('Studds','Democratic','Massachusetts'),
('Stump','Republican','Arizona'),
('Stupak','Democratic','Michigan'),
('Sundquist','Republican','Tennessee'),
('Swett','Democratic','New Hampshire'),
('Swift','Democratic','Washington'),
('Synar','Democratic','Oklahoma'),
('Talent','Republican','Missouri'),
('Tanner','Democratic','Tennessee'),
('Tauzin','Democratic','Louisiana'),
('Taylor (MS)','Democratic','Mississippi'),
('Taylor (NC)','Republican','North Carolina'),
('Tejeda','Democratic','Texas'),
('Thomas','Republican','California'),
('Thomas (WY)','Republican','Wyoming'),
('Thompson','Democratic','Mississippi'),
('Thornton','Democratic','Arkansas'),
('Thurman','Democratic','Florida'),
('Torkildsen','Republican','Massachusetts'),
('Torres','Democratic','California'),
('Torricelli','Democratic','New Jersey'),
('Towns','Democratic','New York'),
('Traficant','Democratic','Ohio'),
('Tucker','Democratic','California'),
('Underwood (GU)','Democratic','(Unknown)'),
('Unsoeld','Democratic','Washington'),
('Upton','Republican','Michigan'),
('Valentine','Democratic','North Carolina'),
('Velazquez','Democratic','New York'),
('Vento','Democratic','Minnesota'),
('Visclosky','Democratic','Indiana'),
('Volkmer','Democratic','Missouri'),
('Vucanovich','Republican','Nevada'),
('Walker','Republican','Pennsylvania'),
('Walsh','Republican','New York'),
('Washington','Democratic','Texas'),
('Waters','Democratic','California'),
('Watt (NC)','Democratic','North Carolina'),
('Waxman','Democratic','California'),
('Weldon (PA)','Republican','Pennsylvania'),
('Wheat','Democratic','Missouri'),
('Whitten','Democratic','Mississippi'),
('Williams','Democratic','Montana'),
('Wilson','Democratic','Texas'),
('Wise','Democratic','West Virginia'),
('Wolf','Republican','Virginia'),
('Woolsey','Democratic','California'),
('Wyden','Democratic','Oregon'),
('Wynn','Democratic','Maryland'),
('Yates','Democratic','Illinois'),
('Young (AK)','Republican','Alaska'),
('Young (FL)','Republican','Florida'),
('Zeliff','Republican','New Hampshire'),
('Zimmer','Republican','New Jersey')




WHILE((SELECT COUNT(*) FROM @_T)> 0)BEGIN
	SET @_R_ID = (SELECT TOP(1) R_ID FROM @_T)
	SET @_MEM_NAME = (SELECT TOP(1) LTRIM(RTRIM(NAME)) FROM @_T WHERE R_ID = @_R_ID)
	SET @_P = (SELECT TOP(1) LTRIM(RTRIM(P)) FROM @_T WHERE R_ID = @_R_ID)
	SET @_S = (SELECT TOP(1) LTRIM(RTRIM(S)) FROM @_T WHERE R_ID = @_R_ID)
	INSERT INTO @_T3
		SELECT MEM_ID, NAME, STATE FROM GET_MEM_ID_FROM_NAME(@_DATE_BILL_VOTED_ON, @_MEM_NAME, @_P, @_S, @_CONG_NUM)
	
	SET @_C = (SELECT COUNT(*) FROM @_T3)
	if @_C = 0
		INSERT INTO @_T4 VALUES(@_MEM_NAME,@_P,@_S,0)
	ELSE
		INSERT INTO @_T2 
			SELECT MEM_ID, NAME, STATE, @_C FROM @_T3
	
	DELETE @_T3
DELETE @_T WHERE R_ID = @_R_ID
END

SELECT * FROM @_T2 order by NUM_RCRDS_RTND, STATE
SELECT * FROM @_T4 order by STATE

