IF OBJECT_ID('GET_MEM_ID_FROM_NAME') IS NOT NULL
    DROP FUNCTION GET_MEM_ID_FROM_NAME
GO
CREATE FUNCTION GET_MEM_ID_FROM_NAME(@_DATE_BILL_VOTED_ON VARCHAR(20), @_MEM_NAME VARCHAR(75),@_P VARCHAR(35), @_S VARCHAR(75),@_CONG_NUM INT)
RETURNS @_T table(R_ID INT IDENTITY(0,1), MEM_ID VARCHAR(20), NAME VARCHAR(512), STATE VARCHAR(3))
BEGIN
DECLARE @_T2 table(R_ID INT IDENTITY(0,1), MEM_ID VARCHAR(20), NAME VARCHAR(512), STATE VARCHAR(3))
DECLARE @_N1 VARCHAR(50),  @_N2 VARCHAR(50), @_ST VARCHAR(4), @_COND INT = 0, @_PRTY VARCHAR(35), @_BILL_VOTE_D DATE
SET @_PRTY = (SELECT SUBSTRING(@_P,1,1))
SET @_BILL_VOTE_D = CONVERT(DATE,@_DATE_BILL_VOTED_ON)


IF @_MEM_NAME like '%,%(%)' BEGIN
	SET @_COND = 1
	SET @_N1 = (SELECT LTRIM(RTRIM(DBO.SPLIT_STRING_GET_IX(@_MEM_NAME,',',0))))
	SET @_N2 = (SELECT LTRIM(RTRIM(DBO.SPLIT_STRING_GET_IX(DBO.SPLIT_STRING_GET_IX(@_MEM_NAME,',',1),'(',0))))
	SET @_ST = (SELECT LTRIM(RTRIM(DBO.SPLIT_STRING_GET_IX(DBO.SPLIT_STRING_GET_IX(@_MEM_NAME,'(',1),')',0))))
END ELSE IF @_MEM_NAME like '%,%' BEGIN
	SET @_COND = 2
	SET @_N1 = (SELECT LTRIM(RTRIM(DBO.SPLIT_STRING_GET_IX(@_MEM_NAME,',',0))))
	SET @_N2 = (SELECT LTRIM(RTRIM(DBO.SPLIT_STRING_GET_IX(@_MEM_NAME,',',1))))
END ELSE IF @_MEM_NAME like '%(%)%' BEGIN
	SET @_COND = 3
	SET @_N1 = (SELECT LTRIM(RTRIM(DBO.SPLIT_STRING_GET_IX(@_MEM_NAME,'(',0))))
	SET @_ST = (select LTRIM(RTRIM(DBO.SPLIT_STRING_GET_IX(DBO.SPLIT_STRING_GET_IX(@_MEM_NAME,'(',1),')',0))))
END ELSE BEGIN
	SET @_COND = 4
	SET @_N1 = LTRIM(RTRIM(@_MEM_NAME))
END

IF exists(SELECT ABBR FROM STATE_LOOK_UP WHERE STATE = @_S)
	SET @_ST = (SELECT ABBR FROM STATE_LOOK_UP WHERE STATE = @_S)

--SELECT @_COND, @_N1, @_N2, @_ST, @_PRTY

IF @_COND = 1
	INSERT INTO @_T (MEM_ID, NAME, STATE)
	select MEM_ID, name, STATE
	from (select DISTINCT a.MEM_ID, STATE,
		iif(not b.sufx is NULL,
			iif(not b.MNAME is NULL, b.FNAME+' '+b.sufx+' '+b.MNAME +' '+ b.LNAME, b.FNAME+' '+b.sufx+' '+b.LNAME),
			b.FNAME+' '+ b.LNAME) as Name
	from CONG_IDS as A
		join MEM_DETAILS as B on a.MEM_ID=b.MEM_ID
		join roles as C on a.MEM_ID=C.MEM_ID
		WHERE C.STATE = @_ST AND CONG_NUM = @_CONG_NUM AND PARTY = @_PRTY AND @_BILL_VOTE_D BETWEEN START_DATE AND END_DATE AND CHAMBER = 'House')as a
	WHERE (NAME LIKE '%'+@_N1+' '+@_N2+'%' OR
		  NAME LIKE '%'+@_N2+' '+@_N1+'%' OR
		  NAME LIKE '%'+@_N2+' % '+@_N1+'%' OR
		  NAME LIKE '%'+@_N1+'%' OR
		  NAME LIKE '%'+@_N2+'%')

IF @_COND = 2
	INSERT INTO @_T (MEM_ID, NAME, STATE)
	select MEM_ID, name, STATE
	from (select DISTINCT a.MEM_ID, STATE,
		iif(not b.sufx is NULL,
			iif(not b.MNAME is NULL, b.FNAME+' '+b.sufx+' '+b.MNAME +' '+ b.LNAME, b.FNAME+' '+b.sufx+' '+b.LNAME),
			b.FNAME+' '+ b.LNAME) as Name
	from CONG_IDS as A
		join MEM_DETAILS as B on a.MEM_ID=b.MEM_ID
		join roles as C on a.MEM_ID=C.MEM_ID
	WHERE CONG_NUM = @_CONG_NUM AND STATE = @_ST AND PARTY = @_PRTY AND @_BILL_VOTE_D BETWEEN START_DATE AND END_DATE AND CHAMBER = 'House' )as a
	WHERE (NAME LIKE '%'+@_N1+' '+@_N2+'%' OR
		  NAME LIKE '%'+@_N2+' '+@_N1+'%' OR
		  NAME LIKE '%'+@_N2+' % '+@_N1+'%')

IF @_COND = 3
	INSERT INTO @_T (MEM_ID, NAME, STATE)
	select MEM_ID, name, STATE
	from (select DISTINCT a.MEM_ID, STATE,
		iif(not b.sufx is NULL,
			iif(not b.MNAME is NULL, b.FNAME+' '+b.sufx+' '+b.MNAME +' '+ b.LNAME, b.FNAME+' '+b.sufx+' '+b.LNAME),
			b.FNAME+' '+ b.LNAME) as Name
	from CONG_IDS as A
		join MEM_DETAILS as B on a.MEM_ID=b.MEM_ID
		join roles as C on a.MEM_ID=C.MEM_ID
		WHERE C.STATE = @_ST AND CONG_NUM = @_CONG_NUM AND PARTY = @_PRTY AND @_BILL_VOTE_D BETWEEN START_DATE AND END_DATE AND CHAMBER = 'House' )as a
	WHERE Name like '% '+@_N1+'%'

IF @_COND = 4
	INSERT INTO @_T (MEM_ID, NAME, STATE)
	select MEM_ID, name, STATE
	from (select DISTINCT a.MEM_ID, STATE,
		iif(not b.sufx is NULL,
			iif(not b.MNAME is NULL, b.FNAME+' '+b.sufx+' '+b.MNAME +' '+ b.LNAME, b.FNAME+' '+b.sufx+' '+b.LNAME),
			b.FNAME+' '+ b.LNAME) as Name
	from CONG_IDS as A
		join MEM_DETAILS as B on a.MEM_ID=b.MEM_ID
		join roles as C on a.MEM_ID=C.MEM_ID
	WHERE CONG_NUM = @_CONG_NUM AND STATE = @_ST AND PARTY = @_PRTY AND @_BILL_VOTE_D BETWEEN START_DATE AND END_DATE AND CHAMBER = 'House' )as a
	WHERE Name like '% '+@_N1+'%'


IF (SELECT COUNT(*) FROM @_T)>1 AND @_COND = 1 BEGIN
	INSERT INTO @_T2 SELECT MEM_ID, name, STATE FROM @_T WHERE SUBSTRING(LTRIM(RTRIM(DBO.SPLIT_STRING_GET_IX(NAME,' ',0))),1,4) LIKE SUBSTRING(@_N2,1,4)+'%' OR
															   SUBSTRING(LTRIM(RTRIM(DBO.SPLIT_STRING_GET_IX(NAME,' ',1))),1,4) LIKE SUBSTRING(@_N2,1,4)+'%' --OR
															   --SUBSTRING(LTRIM(RTRIM(DBO.SPLIT_STRING_GET_IX(NAME,' ',0))),1,4) LIKE SUBSTRING(@_N1,1,4)+'%' OR
															   --SUBSTRING(LTRIM(RTRIM(DBO.SPLIT_STRING_GET_IX(NAME,' ',1))),1,4) LIKE SUBSTRING(@_N1,1,4)+'%'
	IF (SELECT COUNT(*) FROM @_T2)=1 BEGIN
		DELETE @_T
		INSERT INTO @_T SELECT MEM_ID, name, STATE FROM @_T2
	END
END
RETURN
END

--SELECT * FROM GET_MEM_ID_FROM_NAME('Porter')

