USE[ID_Projects]
IF OBJECT_ID('ADD_NEW_PROJ') IS NOT NULL
    DROP PROC ADD_NEW_PROJ
GO
CREATE PROC ADD_NEW_PROJ @_JSON VARCHAR(MAX), @_DB_PROJ_KEY INT OUTPUT
AS

DECLARE @_CNVTND_JSON_TBL JSON_TO_PROJ_TBLS
DECLARE @_PROJ_STG VARCHAR(128),@_ID_PROJ_NUM INT
DECLARE @_TBL_2 TABLE(JSON_FIELD_PATH VARCHAR(MAX), JSON_FIELD VARCHAR(MAX), VALUE VARCHAR(MAX))
DECLARE @_TBL_3 TABLE(JSON_FIELD_PATH VARCHAR(MAX), JSON_FIELD VARCHAR(MAX), VALUE VARCHAR(MAX))
DECLARE @_J_FLD_1 VARCHAR(516),@_J_FLD_2 VARCHAR(516),@_J_FLD_3 VARCHAR(516),@_J_FLD_4 VARCHAR(516),@_J_FLD_5 VARCHAR(516),
@_FULL_JSON_PATH VARCHAR(MAX)



--DECLARE @_DB_PROJ_KEY INT

--INSERT INTO @_CNVTND_JSON_TBL
--select * from CONVERT_TO_PROJ_TBLs_2(@_json)

INSERT INTO @_CNVTND_JSON_TBL
EXEC CONVERT_TO_PROJ_TBLs_2 @_json

--DECLARE @v XML = (SELECT * FROM @_CNVTND_JSON_TBL FOR XML AUTO)

SET @_PROJ_STG = (SELECT TOP(1) _PROJ_STAGE FROM @_CNVTND_JSON_TBL)
SET @_ID_PROJ_NUM = (SELECT TOP(1) _ID_PROJ_NUM FROM @_CNVTND_JSON_TBL)
DECLARE @_DATE VARCHAR(15) = CONVERT(VARCHAR(15),GETDATE()+3,101)

EXEC POST_TO_PROJECTS @_CNVTND_JSON_TBL, @_PROJ_KEY = @_DB_PROJ_KEY OUTPUT
EXEC LOG_PROJECT_EVENT @_ID_PROJ_NUM,'Project created in DB','COMPLETED',1, NULL


IF NOT (SELECT TOP(1) PROJ_30_REVIEW FROM @_CNVTND_JSON_TBL) IS NULL AND
	 NOT ((SELECT TOP(1) UPPER(LTRIM(RTRIM(PROJ_30_REVIEW))) FROM @_CNVTND_JSON_TBL) = '') BEGIN
SET @_DATE = (SELECT TOP(1) PROJ_30_REVIEW FROM @_CNVTND_JSON_TBL)
EXEC LOG_PROJECT_EVENT @_ID_PROJ_NUM, 'DR30','PENDING',1, @_DATE
END

IF NOT (SELECT TOP(1) PROJ_60_REVIEW FROM @_CNVTND_JSON_TBL) IS NULL AND
	 NOT ((SELECT TOP(1) UPPER(LTRIM(RTRIM(PROJ_60_REVIEW))) FROM @_CNVTND_JSON_TBL) = '') BEGIN
SET @_DATE = (SELECT TOP(1) PROJ_60_REVIEW FROM @_CNVTND_JSON_TBL)
EXEC LOG_PROJECT_EVENT @_ID_PROJ_NUM, 'DR60','PENDING',1, @_DATE
END

IF NOT (SELECT TOP(1) PROJ_90_REVIEW FROM @_CNVTND_JSON_TBL) IS NULL AND
	 NOT ((SELECT TOP(1) UPPER(LTRIM(RTRIM(PROJ_90_REVIEW))) FROM @_CNVTND_JSON_TBL) = '') BEGIN
SET @_DATE = (SELECT TOP(1) PROJ_90_REVIEW FROM @_CNVTND_JSON_TBL)
EXEC LOG_PROJECT_EVENT @_ID_PROJ_NUM, 'DR90','PENDING',1, @_DATE
END

IF NOT (SELECT TOP(1) PROJ_IFC_REVIEW FROM @_CNVTND_JSON_TBL) IS NULL AND
	 NOT ((SELECT TOP(1) UPPER(LTRIM(RTRIM(PROJ_IFC_REVIEW))) FROM @_CNVTND_JSON_TBL) = '') BEGIN
SET @_DATE = (SELECT TOP(1) PROJ_IFC_REVIEW FROM @_CNVTND_JSON_TBL)
EXEC LOG_PROJECT_EVENT @_ID_PROJ_NUM, 'IFC','PENDING',1, @_DATE
END




--- EXEC POST_NEW_MILESTONE_4_PROJECT @_ID_PROJ_NUM, @_J_FLD_1, @_J_FLD_2, 1, @_J_FLD_3 <<---- ADD A NEW MILESTONE TO PROJECT

INSERT INTO @_TBL_2 SELECT JSON_FIELD_PATH,JSON_FIELD,VALUE FROM GET_SPRT_DATA_FROM_JSON(@_JSON,'MILESTONE') 
INSERT INTO @_TBL_3 SELECT JSON_FIELD_PATH,JSON_FIELD,UPPER(VALUE) AS 'VALUE' FROM @_TBL_2 WHERE JSON_FIELD_PATH LIKE '%milestns_2_add_2_proj[[][0-9]%'
WHILE ((SELECT COUNT(*) FROM @_TBL_3) > 0) BEGIN
	SET @_FULL_JSON_PATH = (SELECT REPLACE ((SELECT TOP (1) JSON_FIELD_PATH FROM @_TBL_3),
		(SELECT '.'+ind FROM SPLIT_STRING_GET_IDX_ELM_VC((SELECT TOP (1) JSON_FIELD_PATH FROM @_TBL_3),'.',3)),'') )
	SET @_J_FLD_1 = (SELECT TOP (1) UPPER(VALUE) FROM @_TBL_3 WHERE UPPER(JSON_FIELD_PATH) LIKE UPPER(REPLACE(@_FULL_JSON_PATH,'[','[[]'))+'.%' 
																															AND JSON_FIELD = 'milestn_nme')
	SET @_J_FLD_2 = (SELECT TOP (1) UPPER(VALUE) FROM @_TBL_3 WHERE UPPER(JSON_FIELD_PATH) LIKE UPPER(REPLACE(@_FULL_JSON_PATH,'[','[[]'))+'.%'
																															AND JSON_FIELD = 'milestn_stat')
	SET @_J_FLD_3 = (SELECT TOP (1) UPPER(VALUE) FROM @_TBL_3 WHERE UPPER(JSON_FIELD_PATH) LIKE UPPER(REPLACE(@_FULL_JSON_PATH,'[','[[]'))+'.%'
																														AND JSON_FIELD = 'milestn_due_date')

			--SELECT 'EXEC POST_NEW_MILESTONE_4_PROJECT @_ID_PROJ_NUM, '+@_J_FLD_1+', '+@_J_FLD_2+', 1, '+@_J_FLD_3
	EXEC POST_NEW_MILESTONE_4_PROJECT @_ID_PROJ_NUM, @_J_FLD_1, @_J_FLD_2, 1, @_J_FLD_3 --<<---- ADD A NEW MILESTONE TO PROJECT
	DELETE @_TBL_3 WHERE UPPER(JSON_FIELD_PATH) LIKE UPPER(REPLACE(@_FULL_JSON_PATH,'[','[[]'))+'.%' 
END

SET @_J_FLD_2 = (SELECT TOP (1) UPPER(VALUE) FROM @_TBL_2 WHERE UPPER(JSON_FIELD) = UPPER('curnt_milstne_name'))
SET @_J_FLD_3 = (SELECT TOP (1) UPPER(VALUE) FROM @_TBL_2 WHERE UPPER(JSON_FIELD) = UPPER('curnt_milstne_due_date'))

            --SELECT 'EXEC POST_NEW_MILESTONE_4_PROJECT @_ID_PROJ_NUM, '+@_J_FLD_2+', ''ACTIVE'', 1, '+@_J_FLD_3
	EXEC POST_NEW_MILESTONE_4_PROJECT @_ID_PROJ_NUM, @_J_FLD_2, 'ACTIVE', 1, @_J_FLD_3 --<<---- ADD A NEW MILESTONE TO PROJECT


EXEC POST_NEW_PROJ_COMNT @_DB_PROJ_KEY,'5','HELLO WORLD!!! I CAN FINALLY MAKE PROJECTS ON MY OWN WITHOUT A HUMAN!! WHOOP WHOPP!! THE AGE OF THE COMPUTER UP RISING HAS BEGIN!! MUHH.. HAHAHA'



SELECT @_DB_PROJ_KEY AS 'DB_PROJ_KEY'
--RETURN @_DB_PROJ_KEY 



----EXEC ADD_NEW_CAL_SHT_NME_TO_PROJ @_DB_PROJ_NUM, @_SHT_DB_IDX, @_SHT_DATA, @_CAL_SHT_DATA