

IF OBJECT_ID('CHECK_LOGIN_CERTS') IS NOT NULL
    DROP function CHECK_LOGIN_CERTS
GO
CREATE function CHECK_LOGIN_CERTS(@_EMAIL VARCHAR(516), @_PSWD VARCHAR(50))
RETURNS @T TABLE (_AUTH INT, _KEY varchar(1500))
BEGIN
DECLARE @_RTN varbinary(1000), @_DB_ID INT, @_COM_NAME VARCHAR(256),
		@_EMP_ID INT = (SELECT E_DB_IDX_NUM FROM EMPLOYEES WHERE UPPER(LTRIM(RTRIM(EMP_EMAIL_1))) = UPPER(LTRIM(RTRIM(@_EMAIL))) OR UPPER(LTRIM(RTRIM(EMP_EMAIL_2))) = UPPER(LTRIM(RTRIM(@_EMAIL)))),
        @_GST_ID INT = (SELECT NIE_DB_IDX_NUM FROM NON_ID_EMPLOYEES WHERE UPPER(LTRIM(RTRIM(GST_EMAIL_1))) = UPPER(LTRIM(RTRIM(@_EMAIL))) OR UPPER(LTRIM(RTRIM(GST_EMAIL_2))) = UPPER(LTRIM(RTRIM(@_EMAIL))))

IF @_EMP_ID IS NULL BEGIN
	IF @_GST_ID IS NULL
		SET @_DB_ID = 0;
	ELSE
		--GET EMPLOYER NAME
		SET @_COM_NAME = (SELECT B.CUSTOMER_NAME  FROM NON_ID_EMPLOYEES AS A JOIN CUSTOMERS AS B ON A.NIE_DB_IDX_NUM = B.C_DB_IDX_NUM WHERE A.NIE_DB_IDX_NUM = @_GST_ID)
		SET @_DB_ID = (SELECT NIE_DB_IDX_NUM FROM NON_ID_EMPLOYEES 
						   WHERE PASSWORD = (SELECT HASHBYTES('SHA2_512', CONCAT(CONVERT(VARCHAR(516),NIE_DB_IDX_NUM), GST_EMAIL_1, GST_EMAIL_2, @_PSWD, @_COM_NAME)) FROM NON_ID_EMPLOYEES 
											WHERE NIE_DB_IDX_NUM = @_GST_ID))
END ELSE BEGIN
--GET EMPLOYER NAME
	SET @_COM_NAME = (SELECT B.CUSTOMER_NAME FROM EMPLOYEES AS A JOIN CUSTOMERS AS B ON A.E_COM_IDX_NUM = B.C_DB_IDX_NUM WHERE A.E_DB_IDX_NUM = @_EMP_ID)
	SET @_DB_ID = (SELECT E_DB_IDX_NUM FROM EMPLOYEES 
					   WHERE PASSWORD = (SELECT HASHBYTES('SHA2_512', CONCAT(CONVERT(VARCHAR(516),E_DB_IDX_NUM), EMP_EMAIL_1, EMP_EMAIL_2, @_PSWD, @_COM_NAME)) FROM EMPLOYEES 
											WHERE E_DB_IDX_NUM = @_EMP_ID))
END
--RETURN IIF(NOT @_DB_EMP_ID = 0, @_DB_EMP_ID, 0)
--RETURN IIF(NOT @_DB_EMP_ID = 0, (SELECT dbo.GET_USR_ENCRPT_KEY(@_EMAIL)), 0)
IF NOT @_DB_ID = 0
	INSERT INTO @T(_AUTH,_KEY) SELECT 1, convert(varchar(1000),dbo.GET_USR_ENCRPT_KEY(@_EMAIL),2);
ELSE
	INSERT INTO @T(_AUTH,_KEY) SELECT 0,convert(varchar(1000),HASHBYTES('SHA2_512','0'),2);

RETURN
END

--SELECT DBO.CHECK_LOGIN_CERTS('nick.leavitt@industrial-design.us','p@ssw0rd')
