USE[ID_Projects]

IF OBJECT_ID('GET_SPRT_DATA_FROM_JSON') IS NOT NULL
    DROP function GET_SPRT_DATA_FROM_JSON
GO
CREATE function GET_SPRT_DATA_FROM_JSON(@_JSON VARCHAR(MAX), @_JSON_DATA_2_GET VARCHAR(75))
RETURNS @_t table(JSON_FIELD_PATH VARCHAR(MAX),JSON_FIELD VARCHAR(516),VALUE VARCHAR(516))
BEGIN

DECLARE @_JSON_FIELD_CHR VARCHAR(75)


SET @_JSON_FIELD_CHR = (SELECT * FROM SPLIT_STRING_GET_IDX_ELM_VC( 
(SELECT IND FROM SPLIT_STRING_VC(
	(SELECT GLOBAL_VARIABLE_VALUE FROM SYSTEM_GLOBAL_VARIABLES WHERE GLOBAL_VARIABLE_NAME = 'JSON_USR_SLCTD_FIELDS'),',')
WHERE IND LIKE '%'+@_JSON_DATA_2_GET+'%'),'~',1)
)

--SELECT @_JSON_FIELD_CHR

INSERT INTO @_t 
select PATH,Param AS JSON_FIELD, VALUE FROM CONVERT_JSON_DATA_TO_TABLE_3_VC(@_JSON) 
WHERE NOT UPPER(TYPE) = 'OBJECT' AND NOT UPPER(TYPE) = 'ARRAY' AND GenericPath LIKE '%.'+@_JSON_FIELD_CHR+'.%'
-- CHANGED FROM BELOW TO ABOVE ON 3/20/2020
--WHERE NOT UPPER(TYPE) = 'OBJECT' AND GenericPath LIKE '%.'+@_JSON_FIELD_CHR+'.%'


RETURN
END





--SELECT JSON_FIELD,VALUE FROM GET_SPRT_DATA_FROM_JSON(@_JSON,'CUSTOMER')
